version: '3.9'

services:
  postgres:
    image: postgres
    container_name: express_mall_pg
    # restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
